[[redirects]]
    from = "https://princesspandalover.netlify.app/*"
    to = "https://princesspandalover.com/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/tpt2"
    to = "/tpt2/july-2024"
    status = 301
    force = true

[[redirects]]
    from = "/tpt2/index.html"
    to = "/tpt2/july-2024"
    status = 301
    force = true

[[redirects]]
    from = "/tpt2/may_2024"
    to = "/tpt2/may-2024"
    status = 301
    force = true

[[redirects]]
    from = "/tpt2/june_2024"
    to = "/tpt2/june-2024"
    status = 301
    force = true

[[redirects]]
    from = "/tpt2/july_2024"
    to = "/tpt2/july-2024"
    status = 301
    force = true