[[plugins]]
package = "@netlify/plugin-sitemap"

    [plugins.inputs]
        exclude = [
            './sonicverse/*'
        ]

[[redirects]]
    from = "/tp2"
    to = "/tpt2/July_2024.html"
    status = 301
    force = true